<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="AndresLaptop" name="Exercises.LessonTwentyOne.TestWithDataProvider" tests="3" failures="1" timestamp="22 Jan 2023 14:39:07 GMT" time="30.805" errors="0">
  <testcase name="testMethod1" time="19.146" classname="Exercises.LessonTwentyOne.TestWithDataProvider"/>
  <testcase name="testMethod1" time="4.968" classname="Exercises.LessonTwentyOne.TestWithDataProvider"/>
  <testcase name="testMethod1" time="6.691" classname="Exercises.LessonTwentyOne.TestWithDataProvider">
    <failure type="java.lang.AssertionError" message="Verify login success popup detail message expected [Just using for test] but found [You are logged in!]">
      <![CDATA[java.lang.AssertionError: Verify login success popup detail message expected [Just using for test] but found [You are logged in!]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at TestFlow.AllTestFlow.LoginTestFlowWithHardAssert.verifyCorrectEmailAndPassword(LoginTestFlowWithHardAssert.java:77)
at TestFlow.AllTestFlow.LoginTestFlowWithHardAssert.verifyLogin(LoginTestFlowWithHardAssert.java:47)
at TestFlow.AllTestFlow.LoginTestFlowWithHardAssert.performLogin(LoginTestFlowWithHardAssert.java:32)
at Exercises.LessonTwentyOne.TestWithDataProvider.testMethod1(TestWithDataProvider.java:16)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- testMethod1 -->
</testsuite> <!-- Exercises.LessonTwentyOne.TestWithDataProvider -->
